test: testing
FeedAHelp/FeedAHelpless pull request #111
Opened 2023-08-07 16:12 UTC by sojib-sudo

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-08 14:04 UTC, sojib-sudo commented
testing 3 again

2023-08-08 16:05 UTC, TanvirAlam requested changes

2023-08-08 16:05 UTC, TanvirAlam commented on apps/feedahelp/README.md
> +sojib2
why do. have so many times? remove them all , keep only one

2023-08-09 07:12 UTC, TanvirAlam requested changes

2023-08-09 07:14 UTC, TanvirAlam requested changes
![image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/af625d70-7dad-4684-8903-2a9b28968e98)

Your PR should have 3:

```
- test_biplob
- test_sakib
+ test_sojib
```

2023-08-09 07:44 UTC, sojib-sudo commented
> ![image](https://user-images.githubusercontent.com/3250040/259326455-af625d70-7dad-4684-8903-2a9b28968e98.png)
> 
> Your PR should have 3:
> 
> ```
> - test_biplob
> - test_sakib
> + test_sojib
> ```

Okay sit I changed and sent you the PR again, check it out.

2023-08-09 07:49 UTC, merged