feat: Language selection dropdown
FeedAHelp/FeedAHelpless pull request #150
Opened 2023-08-14 14:52 UTC by sojib-sudo

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #104 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-14 15:02 UTC, TanvirAlam requested changes
You PR Heading is wring format:
![image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/fd740aa7-bbcd-4033-857a-02f9c08a0784)

Rename to: `feat: Language selection dropdown`

2023-08-14 15:02 UTC, TanvirAlam commented on apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx
> +          <TranslationDropdown/>
rename this to `<LanguageSelections />`

2023-08-14 15:02 UTC, TanvirAlam commented on apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx
> +          {/* Dropdown  langunage list*/}
delete this comment

2023-08-14 15:06 UTC, TanvirAlam commented on apps/feedahelp/src/components/translationDropdown/TranslationDropdown.tsx
> +
try this,
```
const [isOpen, setIsOpen] = useState(false);

    const toggleDropdown = () => {
        setIsOpen(prev => !prev);
    };

    return (
        <div className='relative flex flex-col items-center rounded-lg'>
            <button
                onClick={toggleDropdown}
                className={`bg-gray-300 p-2 w-full flex items-center justify-center font-bold rounded-lg tracking-wider border-4 border-transparent active:border-white duration-300 ${
                    isOpen ? 'active:text-white' : ''
                }`}
            >
                Languages
                <p className='pl-2'>{isOpen ? '↑' : '↓'}</p>
            </button>
            {isOpen && (
                <div className='bg-gray-300 top-20 flex flex-col items-start rounded-lg p-2 w-full absolute'>
                    {language.map((item, i) => (
                        <div
                            key={i}
                            className='p-2 hover:bg-slate-400 w-full flex cursor-pointer rounded-r-lg border-l-transparent hover:border-l-white border-l-4'
                        >
                            <h3 className='font-bold'>{item?.language}</h3>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
    ```

2023-08-15 07:42 UTC, sojib-sudo commented on apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx
> +          <TranslationDropdown/>
Resolved

2023-08-15 07:42 UTC, sojib-sudo commented on apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx
> +          {/* Dropdown  langunage list*/}
Resolved

2023-08-15 07:42 UTC, sojib-sudo commented on apps/feedahelp/src/components/translationDropdown/TranslationDropdown.tsx
> +
Resolved

2023-08-15 07:46 UTC, TanvirAlam submitted a review, later dismissed
LGTM, lets merge we will fix this when time comes,
nice work @sojib-sudo

2023-08-15 08:14 UTC, TanvirAlam approved these changes, later dismissed

2023-08-15 14:28 UTC, TanvirAlam approved these changes

2023-08-15 14:31 UTC, merged